### ISSUE TITLE
`ChannelDetails.channelId` inconsistent with the rest of the client library IDL

### ISSUE THREAD

**Issue by owenpearson** [ably/docs#1430]
see [internal slack thread](https://ably-real-time.slack.com/archives/CURL4U2FP/p1652783091921479)

In the feature spec we currently call the channel identifier `name` everywhere except for in `ChannelDetails.channelId`. This may be confusing for SDK users since the name `channelId` won't appear anywhere else in the SDK and they may wonder if it means something slightly different from `name`.

It's been suggested that the reason for this difference in naming is due to its use in channel lifecycle events, although since `ChannelDetails` in SDKs are only used for the channel status REST API the same reasoning doesn't apply here.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/EDU-793) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
One potential solution might be to stop sharing the `ChannelDetails` type between lifecycle events and the channel status API. Sharing this type also makes the documentation confusing - for instance the docs says that the channel status REST API returns a `ChannelDetails` but the documentation for `ChannelDetails` suggests that `status` and `occupancy` are optional fields (but for the REST API, at least, they're not).

**Comment by owenpearson** [comment]
It seems to me like we're mostly in agreement that at least for the SDK `Channel.status` method this property should be called `name` although whether this should also be changed on the realtime side is unclear. In the interest of unblocking us from implementing this in the spec, I can see two options:
1. Use the `ChannelDetails.name` property in SDKs (would require realtime team to agree not to remove it until all SDK implementations are changed).
2. Use the `ChannelDetails.channelId` property in SDKs and add a spec point so that SDK implementations will expose this property as `name`. If we were to change the interface on the realtime side later on we would need to at least soft-deprecate the old interface to ensure we don't break the SDKs.

@QuintinWillison @mattheworiordan @paddybyers @SimonWoolf @lmars Can I get your thoughts on this? Or if you don't agree it should be called `name` in SDKs do you have any other suggestions about how we can unblock implementing this in SDKs in the short term?

**Comment by QuintinWillison** [comment]
Given we've only just added this type to the features specification then I would suggest that @owenpearson's option 2 sounds preferable, as this allows the SDK Team to autonomously expose this new API with a more sensible, conformed naming to SDK users (app developers) now.

The service protocol for the REST API being used is already in place so I don't think that this can be changed there without an evolution of that common layer, which should be managed as a breaking change and versioned appropriately (once we've added versioning to `ably-common`, reflecting protocol version).

**Comment by lmars** [comment]
We're currently including both the `name` and `channelId` field in the response from the REST API:

```
$ curl -s -u "${ABLY_API_KEY}" "https://rest.ably.io/channels/example"
{
        "name": "example",
        "channelId": "example",
        "status": {
                "isActive": true,
                "occupancy": {
                        "metrics": {
                                "connections": 0,
                                "publishers": 0,
                                "subscribers": 0,
                                "presenceConnections": 0,
                                "presenceMembers": 0,
                                "presenceSubscribers": 0
                        }
                }
        }
}
```

When I saw this, I thought it was `channelId` that had been deprecated but sticking around, since everywhere else I've interacted with a channel in the API, I've referred to it by `name`.

Personally, I think we should standardise on calling it `name` in all places (REST API, SDK APIs, lifecycle events), and deprecate `channelId`.

I think only @paddybyers has disagreed with this so far, so I'll defer to his opinion on why we can't unilaterally switch to `name`.

**Comment by paddybyers** [comment]
The trigger for trying to standardise on terminology when this was done was that a fully-qualified channel reference has multiple parts: for example the `[meta]log:push` channel has a qualifier part `[meta]`, and the remaining part which we've referred to as the name (ie `log:push`). In the realtime codebase I was working towards consistently using `channelId` as the thing that refers to the fully-qualified channel identifier `[meta]log:push`. And although we've used the channel "name" freely in the documentation, that's not inconsistent with that - most channel identifiers have an empty qualifier part, and so the `channelId` is the name part.

Added to that, we have `name` as a member of `Message`, so for a given message we'll be talking about the name and the channel name, and they're different things.

And we have `clientId`, `connectionId` - what's so alien about `channelId` ?

As for the status API response, I would be ok with it being `{id: xxx, ...}` or `{channelId: xxx, ...}`, but I leant towards `channelId` because there's less opportunity for ambiguity and inconsistency if we're constructing responses in future that refer to channels and other things that also have Ids.

However, note that currently the batch presence response body is:

```
{
  channel: <channelId>,
  presence: [
    ...
  ]
}
```

we might similarly have batch history responses that refer to channels. Should that be:

```
{
  channelId: <channelId>,
  presence: [
    ...
  ]
}
```

?

**Comment by QuintinWillison** [comment]
I had a brief Slack conversation with @paddybyers about this this morning. He shared [this Realtime codebase link (internal)](https://github.com/ably/realtime/blob/main/common/lib/types/scopeid.ts#L244) which includes logic around scope identifiers, though as I said to Paddy, I think this requires a lot more understanding of the Realtime implementation to fully grok implications. What I am seeking is to understand how this ultimately gets exposed to SDK / REST API users.

I've found myself looking at dictionary definitions of "identifier" vs "reference", as I note that Paddy's last comment refers to "fully-qualified" in a couple of places. So, clearly, the qualification-level (is that a term?) of the reference/identifier (Paddy confirmed he's used those words interchangeably in his comment) is important.

I wonder if somebody from the Realtime team, or perhaps @lmars, could help us formulate some ABNF to describe objectively what concepts are involved here. With enough digging I could probably come up with something myself, but I feel I would need some synchronous time with more knowledgable engineers (in terms of our internal code) to do that.

**Comment by owenpearson** [comment]
Closing this now as we've agreed to keep the field as `channelId`
