### ISSUE TITLE
need support article on how to emulate pusher-style mutable auth using token reauth and authCallback

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#147]

**Comment by SimonWoolf** [comment]
context: https://app.intercom.io/a/apps/ua39m1ld/inbox/all/conversations/5573805547

In particular, addressing various auth situations:
- customer's auth server can access canonical list of what channels each client should be able to access at any time — easy, use authUrl
- client needs to be able to request to access new channels, but customer's auth server keeps state on each client — client uses authCallback and names the new channel, if accepted auth server requests a new token with all channels to date
- client needs to be able to request to access new channels, customer's auth server does not keep state, but re-checking permissions is cheap — client keeps list of all channels they want, use authCallback and send that list every time, server re-checks permissions for every channel
- client needs to be able to request to access new channels, customer's auth server does not keep state, but does not want to re-check permissions for every channel each time (the Pusher model) — not sure what to recommend for this

**Comment by paddybyers** [comment]
> client needs to be able to request to access new channels, customer's auth server does not keep state, but does not want to re-check permissions for every channel each time (the Pusher model) — not sure what to recommend for this

Might it be useful to append rights to a token? Ie the client submits a token, and a tokenRequest, and a single token is returned that combines the rights of the two? It would be a very cheap way to do mutable auth.

**Comment by SimonWoolf** [comment]
> Might it be useful to append rights to a token? Ie the client submits a token, and a tokenRequest, and a single token is returned that combines the rights of the two? It would be a very cheap way to do mutable auth.

Good idea :+1: 

Honestly, I'm not sure how much the customer not wanting their server to re-check permissions for every channel each time they want to add a new channel is a real problem, or just a psychological one ('we didn't need to do that for Pusher'). I mean, whatever checking permissions involves for them, I imagine it won't be _that_ expensive an operation. But if we decide it is a problem we want to solve, then sure, that sounds like a decent solution.

**Comment by SimonWoolf** [comment]
Draft support article: https://support.ably.io/solution/articles/3000056545-recommendations-for-incrementally-authorising-new-capabilities. Comments?

**Comment by mattheworiordan** [comment]
> Might it be useful to append rights to a token? Ie the client submits a token, and a tokenRequest, and a single token is returned that combines the rights of the two? It would be a very cheap way to do mutable auth.

Isn't that opening up a security hole in that the server may have decided that client is no longer allowed access to certain channels, but the client can retain them by simply using an old token for every new token request?

@SimonWoolf on your article, I think that's good.  My thoughts are:

* I would make it clear that we have chosen this model because our belief is that a client's servers should always be the canonical source for all permission information.  If permissions are explicitly set and revoked on our servers,  then it is quite plausible that the client's expectations for permissions for a client gets out of sync with what is actually configured for the client i.e. if a request to revoke a privilege failed. As such, by simply getting the most up to date authorisation rules from the client's servers each time the client authenticates, that risk is completely removed and there is never any need to ensure the rules are synchronised between our servers and a client's servers.
* "For most usecases, this simple system is sufficient." perhaps "For most use cases, this simple approach is preferable.".
* Perhaps change "(For 0.8 client libraries this involves an instantaneous disconnect and reconnect, with Ably's connection state recovery feature ensuring no loss of message continuity during this. For 0.9 client libraries a connection can be upgraded seamlessly on the fly)." to "(the auth upgrade is done without any disruption to the connection, however our older 0.8 client libraries would briefly disconnect, reconnect with the new token and [then recover the state](https://support.ably.io/solution/articles/3000044639-connection-state-recovery))"
* "There are several different ways you can handle this with your auth server." perhaps this is an opportunity to break up the article somewhat and introduce a heading such as "Reauthorization strategies:" and perhaps give each strategy a title such as "Auth state retained on client's servers" for the first one.
* On your final note bit, I think it would be useful to a) introduce a new heading such as "Strategy to handle authentication failures", b) explain that by catching an auth failure on a channel the user could in theory reauth at that stage, c) provide a simple example using our JSBin whereby the client connects with a minimal-privileged token, it then attaches to a channel which results in an auth failure, and then upon catching the failure with the expected error code, it reauths and connections.  WDYT?

**Comment by paddybyers** [comment]
> Isn't that opening up a security hole in that the server may have decided that client is no longer allowed access to certain channels, but the client can retain them by simply using an old token for every new token request?

Well the server would obviously validate the given token as well as the token request before issuing the combined one.

**Comment by mattheworiordan** [comment]
> Well the server would obviously validate the given token as well as the token request before issuing the combined one.

You mean our server or the customer's server?  If the former, how would we do that if we have said that Ably will combine privileges?

**Comment by SimonWoolf** [comment]
@mattheworiordan incorporated your feedback, new version: https://support.ably.io/solution/articles/3000056545-recommendations-for-incrementally-authorising-new-capabilities

> Isn't that opening up a security hole in that the server may have decided that client is no longer allowed access to certain channels?

ISTM that if a customer's decided they want to use a model where their auth server neither keeps any state on accumulated capabilities of clients nor re-check every permissions each time they want to add something, then they trade off the ability to effectively revoke permissions. That's an inherent feature of that model, they've swapped revokability for convenience

**Comment by mattheworiordan** [comment]
> That's an inherent feature of that model, they've swapped revokability for convenience

That's fine, but that's not something we play a part in when they allow permissions to be stored client-side and sent to their servers for a new token.  

However, if we allow any token request to be combined within our servers when issuing a new token, then I believe we've opened up a security risk where token privileges meant to be revoked can be held.

**Comment by paddybyers** [comment]
> However, if we allow any token request to be combined within our servers when issuing a new token, then I believe we've opened up a security risk where token privileges meant to be revoked can be held.

I don't understand what situation you're thinking of here.

**Comment by mattheworiordan** [comment]
> Well the server would obviously validate the given token as well as the token request before issuing the combined one.

Re: your questions, can you explain how the server would validate the given token as well as the token request?

**Comment by paddybyers** [comment]
> can you explain how the server would validate the given token as well as the token request?

We're talking about realtime validating a token and a token request submitted together, and issuing a new token with the combined capabilities of the two tokens. The token would be validated in the same way as a token is validated at any other time when submitted by a client. The token request and token would need to be based on the same key, and be for the same clientId; then the capabilities are added together and the expiry time is the minimum (soonest) of the expiry time of the token and the token request.

**Comment by mattheworiordan** [comment]
>  then the capabilities are added together

Right, so if I issue token request A to a user which gives them access to "foo" and "bar" channels, and then later issue them with token request B which gives them access only to "foo", in our current model I can be sure that the user, once they have used token B issued from token request B, will no longer have access to "bar".

However, from what I understand you are proposing, the client can now arbitrarily include token A in their token request with B and now still have access to "bar"?  That is a problem AFAIC because the issuer, not the client, should be deciding on permissions and if necessary merging capabilities, not Ably.

**Comment by paddybyers** [comment]
I agree the model does not allow them to subtract capabilities. That's not why I suggested it. However, it's not a security hole in ably. Even if the app's server decided that it no longer wanted the client to access "foo", the client can still do that using token A, for the remaining lifetime of token A. We're not permitting the client to do anything it wouldn't be able to do otherwise using each token separately.

**Comment by SimonWoolf** [comment]
If Matt's worried about this, how about a slightly tweaked model: allow the inclusion of a token string inside a token request object (maybe a `useCapabilitiesFrom` property), with meaning 'Ably should issue a token with the union of the `capabilities` property and the properties of this token', that must be signed along with the rest of the token request. Then by signing it, their server is explicitly agreeing to allow the capabilities to be unioned.

That has the additional advantage that it can work across token expiries, rather than having to start from scratch once a token expires. Since the token string is just being used as a convenient reference to a capabilities set and not for its actual authentication powers, an auth server could sign a token request with a `useCapabiltiesFrom` tokenstring that's just expired / about to expire, to get the same capabilities as that one

**Comment by paddybyers** [comment]
That proposal still doesn't permit a server to subtract rights without knowing all of the permitted rights.

Anyway, after a persisted token has expired the realtime system has no way of knowing what capabilities it has, or its clientId.

**Comment by mattheworiordan** [comment]
I think we should not be offering this, it has too many problems:

* Removing capabilities is tricky
* Expiring tokens could result in unexpected behaviour
* We're encouraging customers to let us solve a problem that they should be solving themselves.  If they need to keep track of privileges for a client, and won't do that server-side, then they should do it client-side and send to their servers.

If we have mutable auth in the future where we persist capabilities for a `clientId` for example then we can offer this, but until then I think this is the wrong route to go down.

**Comment by mattheworiordan** [comment]
> We're not permitting the client to do anything it wouldn't be able to do otherwise using each token separately.

But then when the original token expires, the capabilities would have to be carried forwards to the next token's expiry, so that's an issue and they are gaining additional privileges then.  If we didn't carry them forward, then this feature is probably not useful in most cases.

**Comment by SimonWoolf** [comment]
The support article is up at https://support.ably.io/solution/articles/3000056545-recommendations-for-incrementally-authorising-new-capabilities and we decided not to go down the appending-rights route, so I think we can close this
