### ISSUE TITLE
syncComplete: fn or attr?

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#223]
Nathaneal pointed out that the spec is inconsistent on whether syncComplete is a function or an attribute: http://docs.ably.io/client-lib-development-guide/features/#RTP13 implies it's a function ("returns..."), but the IDL has it as an attribute.

I don't have a preference as to which it should be. Currently ably-js has it as a function. function'd be more consistent with hasNext() and isLast(), I guess? but don't think it matters much.

**Comment by tcard** [comment]
I don't think it's even meaningful to define functions without arguments that return non-IO values to be defined as functions or attributes. E. g. in Ruby there's no distinction, and Obj-C/Swift allow computed attributes.

I think we should be consistent about it in the IDL and define those as just attributes because it's simpler, but mention on the top that they could be implemented as 0-ary functions if that's more convenient for some reason in any given language.

**Comment by mattheworiordan** [comment]
Well I think it's an attribute in the sense that where a language permits us to define an attribute it is one, and where the language requires a function as an attribute (like Ruby) then it's still an attribute in the sense it's accessible without specific invocation of a method.  Personally I think we should just update the spec to say it's an attribute in `#RTP13`, I don't see any downside.

**Comment by paddybyers** [comment]
I think it's an attribute, except where the language or library implementation doesn't naturally support that. It's not named like you would expect a getter to be named (ie with a verb).

**Comment by mattheworiordan** [comment]
Addressed in https://github.com/ably/docs/issues/248
