### ISSUE TITLE
Spec: Be more explicit about when to discard connection state?

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#287]
Currently, RTN15a says "Connection state is only maintained for a brief period, up to two minutes, so if a client is disconnected for a longer period connection state cannot be resumed". We should probably be more explicit about this and formalise under what conditions clients should and should not attempt to resume, possibly with reference to the last known server-sent activity (see RTN23a), based off the `connectionDetails.connectionStateTtl`. cf https://github.com/ably/ably-js/issues/388

**Comment by mattheworiordan** [comment]
How about we make it a pre-requisite that on resume, the timestamp from the last heartbeat / activity from Ably is included?  That way realtime can decide if it wants to log this as a warning or not i.e. whilst the client library may think there is connection state, the realtime system will in most cases know based on the timestamp.  I appreciate there are clock sync issues, but we could address that quite easily too even by insisting the client lib uses the timestamp received in the connection message perhaps?

**Comment by paddybyers** [comment]
Didn't we already say that the client wouldn't bother attempting a resume if it knew that the interval is too long?

When we move to using `timeSerial`, realtime will know without the client having to specify any additional parameter so I think we can defer this until then.

**Comment by mattheworiordan** [comment]
> Didn't we already say that the client wouldn't bother attempting a resume if it knew that the interval is too long?

Yes, but there are conditions I am sure where it fails to connect, reattempts the connection as part of our fallback strategy, then connects say 15s later with a timestamp that has definitely expired.  In that  case, the realtime system no longer needs to log warnings about connection state not being found because it's completely valid.  

> When we move to using timeSerial, realtime will know without the client having to specify any additional parameter so I think we can defer this until then.

But that won't apply to heartbeats, and especially native WS heartbeats

**Comment by SimonWoolf** [comment]
> Yes, but there are conditions I am sure where it fails to connect, reattempts the connection as part of our fallback strategy, then connects say 15s later with a timestamp that has definitely expired. 

True, but I can't imagine that happens very often -- the client lib would have to go through multiple unsuccessful connection cycles, then have the cycle that ends up succeeding start before the two minute mark but only succeed after. Seems a shame to spend another connect param just to avoid a warning in that event.

(We could perhaps decide to have realtime send a connectionStateTtl that's just a couple of seconds less than the time it'll actually keep the connection state for, to allow for connection time etc?)

**Comment by paddybyers** [comment]
> But that won't apply to heartbeats, and especially native WS heartbeats

True. It won't apply to either because only a `MESSAGE` or `PRESENCE` will have a `timeSerial`.

The other thing we can do is to downgrade the log message, but track the rate, and detect regressions when we see an increase in the rate. We're not paying attention to individual occurrences of the log message anyway, so tracking the rate is going to be more effective in any case.
