### ISSUE TITLE
Max channels per connection

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#387]
We don't have any support article specifically addressing max channels per connection, see https://support.ably.io/search/solutions?term=limits%20channels.

This is covered in https://support.ably.io/solution/articles/3000053845-do-you-have-any-connection-message-rate-or-other-limits-on-accounts-, however I don't think it's obvious someone will find that.

Can we find out what error specifically is returned to the user and document that along with some info on why we limit channels per connection with a link to https://support.ably.io/solution/articles/3000053845-do-you-have-any-connection-message-rate-or-other-limits-on-accounts- to see the exact limits?

Note: @paddybyers @SimonWoolf I would really like to bump https://github.com/ably/wiki/issues/142 up the list as it will help these types of problems. See support ticket 2750

**Comment by paddybyers** [comment]
```
new ErrorInfo(`Maximum number of channels per connection (${maxChannels}) exceeded`, 90010, 400));
```

**Comment by tomczoink** [comment]
Why is it we implement a limit on max number of channels per connection? Basic draft lacking explanation is here: https://support.ably.io/solution/articles/3000075165-is-there-a-maximum-number-of-channels-per-connection-

**Comment by paddybyers** [comment]
As the number of channels attached to a single connection grows, then the size of the connection state grows, as does the work required to resume or recover the connection if it drops, both for the client and the Ably server. We impose a limit to ensure that the connection state, and the load imposed for connection resumption don't become unbounded.

**Comment by tomczoink** [comment]
https://support.ably.io/solution/articles/3000075165-is-there-a-maximum-number-of-channels-per-connection- is the article for this providing the requested information.

**Comment by mattheworiordan** [comment]
Thanks for updating this article.

However, I have some comments:

* Users will not see an error message `Maximum number of channels per connection MAXCHANNELS exceeded` as MAXCHANNELS is a variable.  I would make that cleqarer.  Additionally, why have you not included the error code which is unique (and will not change when the message may), and perhaps use a fixed size font to highlight this is console output.
* You describe why the limits exist, but I don't really think you are putting yourself in the position of a person who has hit this issue.  What can they do about this?  Is this expected behaviour?  Can then upgrade to have higher limits?  
* Please don't use links like "click here".  They are both bad from a UX perspective (you have to read the text next to the link to find out what the link is for), and bad from a search engine perspective (how does it know what the link is about).  Please only use links that describe where you are taking the user.
* Perhaps mention all limits are configurable for Enterprise accounts with a link to find out more?

**Comment by tomczoink** [comment]
I've updated the page per @mattheworiordan's feedback

**Comment by SimonWoolf** [comment]
@tomczoink I'd suggest maybe expanding further on what the developer can do about this. Like, since this is a limit we impose for system health, the main call-to-action shouldn't be an enterprise upsell, it should be working around it in a different way. That way will depend on why they have lots of channels open:

- If they're keeping connections open for a long time, attaching to many channels and not detaching once they've finished using them, they can just do that, using channel#detach ( https://www.ably.io/documentation/realtime/channels-messages#detach ). If using a realtime client library, then publishing or subscribing to a channel will implicitly attach to it (except with recent versions of ably-js, where publishing to a channel that isn't attached is possible -- but the attachment is still happening behind the scenes, it's just transient; if you try to publish to 300 channels at once you'll still run into that limit. You just don't have to manually detach).

- If they only need to publish and not subscribe, and the publish rate for any one particular channel is low, they may want to consider using REST publishes (which are stateless) rather than Realtime publishes -- see the 'publish patterns' section of https://support.ably.io/support/solutions/articles/3000060319-should-i-use-the-rest-or-realtime-library- .

- If they genuinely need to be attach to many hundreds of channels simultaneously with one client, they should consider sharding the channels across multiple connections.

**Comment by tomczoink** [comment]
Updated article per @SimonWoolf's feedback.

**Comment by tomczoink** [comment]
All feedback was applied and still relevant having checked with Affrica on Business vs Enterprise changes, so closing this.
