### ISSUE TITLE
Using presence with lots of members present, and a few members subscribing

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#445]
Whilst we touch on this use case in https://support.ably.io/solution/articles/3000060623-why-do-you-have-a-limit-on-the-number-of-members-present-on-a-channel-, we should create a solution article that explains how we advise developers use presence when they want lots of people being present on a channel, and only a few people or just their servers subscribing for presence changes.

**Comment by Srushtika** [comment]
This is explained in the Best Practice Guide: https://www.ably.io/documentation/best-practice-guide#being-present-without-subscribing-to-presence

I've also added the same in a support article https://support.ably.io/solution/articles/3000082755-how-can-i-implement-presence-subscriptions-efficiently-in-terms-of-limits- so that it's embeddable from Intercom chats as well.
