### ISSUE TITLE
Terminology clean up

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#49]
Whilst working through the documentation today, I found that referring to clients that have a `clientId` as authenticated clients could be very confusing for users.  This is probably because being `authenticated` has no relation to your authentication with Ably via a token or API key, and the word authentication exists in Basic Authentication as well.

Having had a quick chat about this, @paddybyers and I came up with the following suggestion, which should not have any impact on the client libraries fortunately, but will simply be rolled out in our documentation.

@SimonWoolf and @lmars, do you have any objections or suggestions to improve this terminology?

### Authentication

The process of providing credentials to Ably in the form of a token or API key, which in turn allows you to communicate with Ably if the credentials are valid.

### Authorisation

Ably is responsible for authorising or refusing operations for the authenticated client based on the permissions specified within the API key and/or Token provided when the client authenticated.

### Identified Client

Any client that has connected to Ably and has either explicitly provided a `clientId` when instancing the library, or implicitly been assigned a `clientId` following token authentication, will then assume and be restricted to that `clientId` for all operations. As our customers are responsible for issuing tokens or token requests themselves, and we recommend that they only use token authentication and never share their private keys with clients, an identified client publishing or present on a channel with the `clientId` given in their token can therefore be trusted by other clients.

**Comment by lmars** [comment]
LGTM

**Comment by paddybyers** [comment]
Because people get especially pedantic when it comes to these things, I think we need to make sure the definitions of these terms are accurate and unambiguous in the docs.

(I wrote these and now I'm not sure if they're too pedantic, but whatever.)

Authentication

The process of deciding, based on the presented credentials, whether or not an entity may interact with the service. The credentials may be presented explicitly (eg using HTTP Basic Authentication) or in some cases the entity may prove possession of the credentials (eg with the signed body of a `requestToken` request). In Ably credentials are either an API key or a auth token.

Authenticated client

A client of the Ably service that has been successfully authenticated.

Authorisation

The process of deciding whether or not a given entity (usually authenticated) is allowed to perform a given operation. In Ably, authorisation for most operations is based on the Capabilities associated with the key or token that was used to authenticate a client.

Identified client

An authenticated client with a specific claimed client identity, or `clientId`, whose credentials are verified as confirming that identity. In Ably a client can be identified with a `clientId` in three ways:

- if the client authenticated with a token that is issued for that `clientId`;
- if the client  claims that `clientId` and is authenticated with an API key ("basic auth");
- if the client claims that `clientId` and is authenticated with a token that is issued for the wildcard `clientId`.

We encourage customers to issue tokens so that all clients authenticate using a token and do not have access to API keys. Since the customer can then control the `clientId` that may be used by any of its clients, all other clients can rely on the validity of the `clientId` in published messages and of members present in presence channels.

**Comment by mattheworiordan** [comment]
Thanks @paddybyers, very good

**Comment by mattheworiordan** [comment]
Done
