### ISSUE TITLE
Clarify RSA9b

### ISSUE THREAD

**Issue by paddybyers** [ably/docs#509]
It says (in relation to `Auth.createTokenRequest()`)

> Supports all `AuthOptions`

ISTM that `queryTime` is the only option relevant to `TokenRequest` creation.

**Comment by SimonWoolf** [comment]
It's not quite the only one because per RSA9h, a passed in authOptions will be used instead of the persisted authOptions. So e.g. you can pass in a `key` to create a token from that key.

But, well, that's covered by RSA9h. And queryTime support is covered by RSA9d ("will retrieve the server time if queryTime is true"). So not sure there's really any point to RSA9b at all, it's both vague and redundant. Any objections to just deleting it?

**Comment by paddybyers** [comment]
> Any objections to just deleting it?

No
