### ISSUE TITLE
msgSerial reset 

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#661]
Shouldn't the client lib internal message serial always be reset if the connection is closed or becomes failed?  I don't see why it would be valid to start from the previously used `msgSerial` for an entirely new connection.

@paddybyers @SimonWoolf do you agree?

**Comment by paddybyers** [comment]
I think it's a bit more complex than that, because when you attempt a resume you don't know until you get the `CONNECTED` response whether you've got a new connection or not. It's only at that point that you can know whether or not to reset the msgId.

If the msgId isn't set in any pending messages until that information is known, then I think it's fine, irrespective of how the previous connection ended. So yes, you could always reset when the connection is `closed` or `failed`, but that's not really relevant if you always end up resetting once a connection is complete if it's a clean connection.

**Comment by mattheworiordan** [comment]
I think what you’re describing re msgSerial and reconnecting is covered in https://docs.ably.io/client-lib-development-guide/features/#RTN15c3 in fact. 

I am only talking about the scenario where a connection is explicitly closed or becomes failed.

**Comment by SimonWoolf** [comment]
I agree

PR: https://github.com/ably/docs/pull/664
