### ISSUE TITLE
Question about RTP8g (presence#enter on a DETACHED channel)

### ISSUE THREAD

**Issue by SimonWoolf** [ably/docs#67]
So `RTP8g` says that the client lib, for Presence#enter, `Raises an exception if the channel is DETACHED or FAILED`.

This seems inconsistent with other actions that trigger an implicit attach (eg channel#publish), for which the client lib triggers an implicit attach for a `detached` channel just as for an `initialized` one. Presence#enter is the only action that has both an `Implicitly attaches to the channel if not attached` and a `Raises an exception if the channel is DETACHED or FAILED` requirement (the only other action that has the latter is `Presence#get`, which does not have an implicit attach requirement).

Current client lib behaviour: ably-js treats `detached` and `initialized` channels the same for all of these, and implicitly attaches. Ably-ruby has all presence broadcast-type actions raising an exception if called on a `detached` channel.

Not obvious to me why implicit attaching should behave differently between presence actions and others.

(Also for realtime presence#get: if we don't want to make it an implicit-attach action, shouldn't it raise an exception if in any state other than `attached`, not just `detached` or `failed`?)

**Comment by mattheworiordan** [comment]
Ok, so my view is that implicit attach should only happen the first time a channel is accessed i.e. when it is initialised.  If it is has been detached manually by the developer, then I don't think it should reattach without an explicit request to do so.  So if there are inconsistencies in this, we should fix it in the spec.

In regards to whether `Presence#get` should implicitly attach, I think it should.

So my vote would be to ensure consistency in the spec for `Realtime.Channel#subscribe`, `Realtime.Channel#publish`, `Realtime.Presence#enter*`, `Realtime.Presence#leave*`, `Realtime.Presence#update*` in that:

* Calling the method implicitly attaches the channel if the channel is `INITIALISED`
* Raises an exception if the channel is `DETACHED` or `FAILED`

**Comment by paddybyers** [comment]
We are going to have an implicit attach mode (following from Skybet use-case) whereby operations such as `publish()` will create a channel and attach to it, in a way that will lapse after a period of inactivty. When the channel times out there will be a `DETACHED` event from the server to the client, and naturally I think then that the channel in the client would go into the `detached` state.

Now the next event that triggers an implicit attach should not fail.

So, to go with @mattheworiordan's suggestion above we would need two different `detached` states; one that resulted from an explicit `detach()`, and one that resulted from a lapsed implicit attachment. Apart from there being two states, you'd also have the possible race condition which results in you not being quite sure which of the `detached` states you're in.

So now I question why it is helpful to a developer to refuse to re-attach after an explicitly detached channel. So he called `detach()`, say, and then calls `publish()`. Why refuse to do that? Because we think he didn't really mean to call it?

So overall I think implicit attach should be possible from `detached`.

I agree in respect of `get()`.

**Comment by mattheworiordan** [comment]
> We are going to have an implicit attach mode (following from Skybet use-case) whereby operations such as publish() will create a channel and attach to it, in a way that will lapse after a period of inactivty. 

I did not think we ever discussed that.  I am pretty certain we agreed that as an optimisation you could attach to a channel only for publishing purposes, see https://github.com/ably/wiki/issues/35

> Now the next event that triggers an implicit attach should not fail.

As above, I don't think we should ever explicitly detach a channel that a client has attached to.

> So, to go with @mattheworiordan's suggestion above we would need two different detached states; one that resulted from an explicit detach(), and one that resulted from a lapsed implicit attachment. 

If we implement above we don't need this complexity

> So now I question why it is helpful to a developer to refuse to re-attach after an explicitly detached channel. 

That is a good question.  However, I would argue that the reason we allow someone to publish or subscribe to a channel that they never explicitly attached to is a convenience for a common pattern of `channel = client.channels.get(x); channel.publish(y)`.  We are just saving developers one line of code because in almost every case I can imagine, this is what the developer would expect.

However, if a developer has explicitly detached a channel, then I do question why they would unwittingly publish to that detached channel i.e. they are clearly fully aware of the attach and detach capability.

**Comment by paddybyers** [comment]
> they are clearly fully aware of the attach and detach capability

They were probably aware of it also when they called `publish()` without bothering to attach explicitly but knew it wasn't necessary to call it. I just don't see that it addresses any use-case that matters, and it is an inconvenience in all other cases. The only time it would be of value is if he called `detach()` with the intention that later calls to `publish()` from elsewhere in his code would fail. I don't think that's a use-case we should be supporting when it creates inconvenience (and arguably is counter-intuitive) in lots of other cases.

**Comment by mattheworiordan** [comment]
> I don't think that's a use-case we should be supporting when it creates inconvenience (and arguably is counter-intuitive) in lots of other cases.

Ok, I don't particular have a problem that, it does mean another change to most libraries though :(

>> We are going to have an implicit attach mode (following from Skybet use-case) whereby operations such as publish() will create a channel and attach to it, in a way that will lapse after a period of inactivty.

> I did not think we ever discussed that. I am pretty certain we agreed that as an optimisation you could attach to a channel only for publishing purposes, see ably/wiki#35

What are your thoughts on that?

**Comment by SimonWoolf** [comment]
> In regards to whether Presence#get should implicitly attach, I think it should.

Bear in mind that Presence#get doesn't wait for SYNC by default (RTP11a), so a `get` that implicitly attaches will always return [] (as the sync hasn't started), which is a bit counterintuitive.

We could have a different default for `wait_for_sync` if the `get` triggers an attach (pretty messy), or change the default for wait_for_sync?

**Comment by paddybyers** [comment]
> > > We are going to have an implicit attach mode (following from Skybet use-case) whereby operations such as publish() will create a channel and attach to it, in a way that will lapse after a period of inactivty.

> >  I did not think we ever discussed that. I am pretty certain we agreed that as an optimisation you could attach to a channel only for publishing purposes, see ably/wiki#35

> What are your thoughts on that?

We will introduce attach flags, so an explicit attach by the client will indicate which operations on the channel are anticipated (publish, subscribe, presence).

An explicit attach (explicit in the sense that the client requested it via an `ATTACH` message; I'm not yet talking about what in the API triggered that) for `publish` works as it does now, in that it "reserves" the channel, and the client knows that all messages will be published with predictable (and minimum) latency all the time that the channel is active; and when no longer required he explicitly does a `DETACH`.

But I think there is a specific use-case where we do want a attach-on-demand (or implicit attach) mode whereby the association with the channel is created on demand (in response to a `MESSAGE` protocol message, without prior `ATTACH`) and that association can lapse through inactivity. Clearly this doesn't apply if the client wants subscribe and/or presence operations as well, but can apply if it is publish-only.

So my proposal is that when such an implicit attach happens there is an `ATTACHED` sent to the client, and a corresponding `DETACHED` when it lapses. I don't think that is inconsistent with what's described in https://github.com/ably/wiki/issues/35.

We should move this discussion over there.

**Comment by mattheworiordan** [comment]
> Bear in mind that Presence#get doesn't wait for SYNC by default (RTP11a), so a get that implicitly attaches will always return [] (as the sync hasn't started), which is a bit counterintuitive.

True.  I personally prefer to have `waitForSync` true anyway, but if I recall @paddybyers was not keen on  that?  If not, I don't think it's necessarily a big problem if it returns an empty set as the documentation will state it does not wait for SYNC, so calling it on a channel that just attached (whether implicit or explicit) will always be empty

**Comment by SimonWoolf** [comment]
@mattheworiordan what are the usecases for calling `get` without `waitForSync: true`? The only times when the default behaviour is faster than waiting for sync are when the results it returns are incomplete, inaccurate, or both. (And if someone wants results as they come in, that's what `on('present')` is for).

**Comment by mattheworiordan** [comment]
> what even are the usecases for calling get without waitForSync: true?

I am at a loss myself, I recall having this discussion with @paddybyers and his preference was this way round

**Comment by mattheworiordan** [comment]
I believe this is now resolved with https://github.com/ably/docs/commit/440a3a8117d7f5512f96a4a48c2bb31da0211e20. Shout if you don't think so.  All other features discussed in this issue may form part of the 0.9 spec
