### ISSUE TITLE
Add public `Auth.currentTokenDetails`

### ISSUE THREAD

**Issue by paddybyers** [ably/docs#671]
Some existing libraries expose the current `TokenDetails` publically whereas they are private in others. 

It is proposed that we add a public field `currentTokenDetails` to expose the `TokenDetails`, if any, that the library is using and considers to be valid.

**Comment by mattheworiordan** [comment]
@paddybyers should it not just be `currentToken` to allow for JWT, token strings, and token objects?

**Comment by SimonWoolf** [comment]
fwiw ably-js exposes token strings by wrapping them as a minimal tokenDetails object, i.e. `{token: <token>}`. (and jwt similarly since the client lib can't tell a token string from a jwt token). Probably a bit nice than having a property that might be a `tokenDetails` or a `string`, esp for strongly-typed langs

**Comment by mattheworiordan** [comment]
Good point, probably better to have a `TokenDetails` object then./

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/docs/pull/673
