### ISSUE TITLE
Channel docs missing `get()` method in API ref

### ISSUE THREAD

**Issue by Srushtika** [ably/docs#724]
We use the `channel.get()` method frequently but it doesn't seem to be documented:
https://www.ably.io/documentation/realtime/channels
<img width="167" alt="Screenshot 2019-09-04 at 15 52 13" src="https://user-images.githubusercontent.com/5900152/64266153-0c193500-cf2c-11e9-8673-c2b7578542af.png">

**Comment by paddybyers** [comment]
Do you mean `channels.get()` ?

There is a docs entry for the `channels` member of REST or Realtime (https://www.ably.io/documentation/rest/usage#channels) but it just says it's a collection, and doesn't make the API explicit.

**Comment by Srushtika** [comment]
But it should be defined as a method in the API reference for channels, like `subscribe()` or `on()`, right @paddybyers ?

**Comment by paddybyers** [comment]
`get()` is a method on the `channels` object, not a method on any instance of `Channel`.

Currently the `channels` object is documented - to the limited extent that it is - in the "Constructor and usage" section, because it's an attribute of the main REST or Realtime library instance.

I don't mind whether the additional detail is documented where it is now, or in the `Channels` page so long as it is clear, and there's no confusion between what methods exist on the `channels` collection, versus the methods that exist on a single channel.

Note that we have not declared the type of `channels` anywhere, so I suppose we need to do that.

**Comment by Srushtika** [comment]
ok, thanks @paddybyers. Will do.
