### ISSUE TITLE
Token ClientOption should allow Token, TokenDetails or TokenRequest

### ISSUE THREAD

**Issue by mattheworiordan** [ably/docs#75]
Currently `ClientOption#token` only supports a `Token` or `TokenDetails` object.  It should also support a `TokenRequest` given `authUrl` and `authCallback` both support all three

**Comment by mattheworiordan** [comment]
Optionally a client library should be instanceable with just a TokenDetails object, like we do for API Key string or Token string, where the language permits

**Comment by SimonWoolf** [comment]
I'm happy with the first (initing with {token: <tokenRequest>}) :+1:

Not sure about the second (initing with just a tokenDetails) -- means in weakly-typed languages we'd have to guess whether an object passed to the constructor is a tokenDetails or a clientOptions. `{tokenDetails: <tokenDetails>}` isn't much to ask

**Comment by mattheworiordan** [comment]
> Means in weakly-typed languages we'd have to guess whether an object passed to the constructor is a tokenDetails or a clientOptions. 

No, you only need to check if:

* It's a string it's a token string 
* If it's an object, check if it has a `token` attribute, then it's a `TokenDetails`
* Else if it's an object, it's a `TokenRequest` object.

That same logic exists for `authUrl` now.

Not sure why you'd need to determine if its a `ClientOptions` or not?

**Comment by SimonWoolf** [comment]
@mattheworiordan

>> Not sure about the second (initing with just a tokenDetails) --  means in weakly-typed languages we'd have to guess whether an object passed to the constructor is a tokenDetails or a clientOptions

> That same logic exists for authUrl now. Not sure why you'd need to determine if its a ClientOptions or not?

Your're justifying your first proposal (initing with `{token: <tokenRequest>}`). I completely agreed with that, which is why I :+1:'d it. My objection was to your second proposal, that "*Optionally a client library should be instanceable with just a TokenDetails object, like we do for API Key string or Token string*".

If you instance a client library with an object, currently that's assumed to be a clientOptions (in weakly-typed languages). clientOptions and tokenDetails can both have `token` and `clientId` attributes. We could guess based on the presence of `expires` or `issued`, but that's starting to get messy. (Especially if we take it it to its logical conclusion and allow initing with a bare tokenRequest object too - and if we don't, we've just introduced an inconsistency of the same kind that we've just removed with your first proposal!).  `{token: <tokenDetails>/<tokenRequest>}` isn't too much to ask.

(I'd have no objection to the second proposal if it applies only to strongly typed languages where there's no need for guesswork)

**Comment by tcard** [comment]
> ClientOption#token [...] should also support a TokenRequest given authUrl and authCallback both support all three

👍 

> (I'd have no objection to the second proposal if it applies only to strongly typed languages where there's no need for guesswork)

I believe that would be the first time we support different things in different kinds of languages. I don't think it's worth it to break it, it's potentially a slippery slope.

**Comment by tcard** [comment]
Additionally, we can support it everywhere but define that in JavaScript and friends the argument is considered a TokenDetails or TokenRequest only if `instanceof`, `ClientOptions` otherwise.

**Comment by mattheworiordan** [comment]
@SimonWoolf sorry, my comment `Optionally a client library should be instanceable with just a TokenDetails object, like we do for API Key string or Token string, where the language permits` was flippantly suggested back in Jan!  I didn't even notice that and was only focussed on https://github.com/ably/docs/issues/75#issue-122468450.  I don't think we need to support a token object, just a token string. 

Sorry for the confusion both.

**Comment by SimonWoolf** [comment]
> we can support it everywhere but define that in JavaScript and friends the argument is considered a TokenDetails or TokenRequest only if `instanceof`

:-1: TokenDetails and TokenRequest objects in the js lib are currently plain JS objects ducktyped by their properties. That's probably not something we'd be looking to change at this point - for one thing that's how the js world (especially frontend devs) seems to generally expect things to work, for another that'd move 0.9 from being a technically-breaking change (that will still work for 95% of people with no changes), to being a this-will-*definitely*-break-your-code change.

And for what goal? The only point of being ably to do `new Ably.Realtime(tokenRequest) rather than `new Ably.Realtime({token: tokenRequest})` is to save a few characters for simplicity. If we have to do `new Ably.Realtime(Ably.Realtime.TokenRequest.fromJson(tokenRequest))` is worse for simplicity.

In any case, we can't use `instanceof` due to how we're using node VM contexts; see past discussion [here](https://github.com/ably/ably-js/pull/120#issuecomment-138517666).

**Comment by SimonWoolf** [comment]
Anyway, given Matt's clarification, this is a moot point. We all agree with the original suggestion (https://github.com/ably/docs/issues/75#issue-122468450) :slightly_smiling_face:

**Comment by mattheworiordan** [comment]
Ok, so we are all agreed then :) @SimonWoolf fancy a spec PR?

**Comment by funkyboy** [comment]
Implemented in iOS:

**Comment by SimonWoolf** [comment]
This was fixed by https://github.com/ably/docs/pull/207 and merged into the 1.1 integration branch https://github.com/ably/docs/pull/258
